name: Genset RUNNER

on:
  workflow_run:
    workflows: ["Genset CI"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker container
        run: sudo docker pull resya202/genset-next:latest

      - name: Delete old Docker container
        run: sudo docker rm -f genset-next-container || true

      - name: Prune unused Docker resources
        run: |
          sudo docker system prune -af --volumes

      - name: Run Docker container on port 81
        run: sudo docker run -d -p 81:3000 --name genset-next-container resya202/genset-next:latest
