name: Genset RUNNER

on:
  workflow_run:
    workflows: ["Genset CI"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: pull docker container
        run: sudo docker pull resya202/genset-next:latest

      - name: delete old docker container
        run: sudo docker rm -f genset-next-container || true

      - name: run docker container
        run: sudo docker run -d -p 80:3000 --name genset-next-container resya202/genset-next:latest
